services:
  docs:
    image: mym_services_local_docs
    container_name: mym_services_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./mym_services:/app/mym_services:z
    ports:
      - '9000:9000'
    command: /start-docs
