# Generated by Django 4.2.13 on 2024-06-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_remove_user_name_user_created_user_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Número de RUC'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='ruc_number',
            field=models.CharField(db_index=True, max_length=11, verbose_name='Número de RUC'),
        ),
    ]
