# Generated by Django 4.2.13 on 2024-06-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_company_ruc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Celular'),
        ),
    ]
