# Generated by Django 4.2.13 on 2024-06-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contact_email_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=9, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(db_index=True, max_length=9, verbose_name='Celular'),
        ),
    ]
