# Generated by Django 4.2.13 on 2024-06-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_contact_phone_alter_historicalcontact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='full_names',
            field=models.CharField(max_length=100, verbose_name='Nombres completos'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='full_names',
            field=models.CharField(max_length=100, verbose_name='Nombres completos'),
        ),
    ]
