# Generated by Django 4.2.13 on 2024-06-18 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_contact_full_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El número debe empezar con 9 y contener exactamente 9 dígitos.', regex='^9\\d{8}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe empezar con 9 y contener exactamente 9 dígitos.', regex='^9\\d{8}$')], verbose_name='Celular'),
        ),
    ]
