# Generated by Django 4.2.13 on 2024-06-19 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_contact_phone_alter_historicalcontact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe empezar con 9 y contener exactamente 9 dígitos.', regex='^9\\d{8}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe empezar con 9 y contener exactamente 9 dígitos.', regex='^9\\d{8}$')], verbose_name='Celular'),
        ),
    ]
